# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Dontnumber' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  it 'dontnumber' do
    @driver.get('http://127.0.0.1:3000/number/input')
    @driver.find_element(:id, 'arr').click
    @driver.find_element(:id, 'arr').send_keys('sdf')
    @driver.find_element(:id, 'arr').send_keys(:down)
    @driver.find_element(:id, 'arr').send_keys('sdf')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'result').click
    expect(@driver.find_element(:id, 'result').text).to eq('Result is: don\'t numbers')
  end
end
