# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Number628161' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  it 'number628161' do
    @driver.get('http://127.0.0.1:3000/number/input')
    @driver.find_element(:id, 'arr').click
    @driver.find_element(:id, 'arr').send_keys('6 28 1 3 28')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:id, 'result').click
    expect(@driver.find_element(:id, 'result').text).to eq("Array: 6,28\nArray: 28\nmax length:2\nArray with max length:6,28")
  end
end
