# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Nil' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  it 'nil' do
    @driver.get('http://127.0.0.1:3000/number/input')
    @driver.find_element(:id, 'arr').click
    @driver.find_element(:id, 'arr').send_keys(:enter)
    @driver.find_element(:css, 'html').click
    expect(@driver.find_element(:id, 'result').text).to eq('Result is: input nil')
  end
end
