# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Nils' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  it 'nils' do
    @driver.get('http://localhost:3001/')
    @driver.find_element(:id, 'arr').send_keys('')
    @driver.find_element(:id, 'arr').send_keys(:enter)
    @driver.find_element(:css, 'html').click
    expect(@driver.find_element(:css, 'body').text).to eq('Invalid request parameters(arr = input nil)')
  end
end
