# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test2' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  it 'test2' do
    @driver.get('http://localhost:3001/')
    @driver.find_element(:css, '.form-check:nth-child(3) > .form-check-label').click
    @driver.find_element(:id, 'arr').send_keys('6')
    @driver.find_element(:name, 'commit').click
    expect(@driver.find_element(:xpath, '//elem[@type=\'integer\']').text).to eq('6')
  end
end
