# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test1s' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  it 'test1s' do
    @driver.get('http://localhost:3001/')
    @driver.find_element(:id, 'arr').send_keys('6 28 1 3 28')
    @driver.find_element(:name, 'commit').click
    @driver.find_element(:css, 'html').click
    expect(@driver.find_element(:css, 'tbody:nth-child(2) th:nth-child(2)').text).to eq('6 28')
  end
end
