# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'Test1x' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  it 'test1x' do
    @driver.get('http://localhost:3001/')
    @driver.find_element(:css, '.form-check:nth-child(3) > .form-check-label').click
    @driver.find_element(:id, 'arr').click
    @driver.find_element(:id, 'arr').send_keys('6 28 1 3 28')
    @driver.find_element(:name, 'commit').click
    sleep 5
    expect(@driver.find_element(:xpath, '(//elem[@type=\'integer\'])[2]').text).to eq('28')
  end
end
